services:
  - type: web
    name: detector-placas
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_api:app
    envVars:
      - key: FLASK_ENV
        value: production
